config/routes.rb
DiagramRailsApp::Application.routes.draw do
  resources :jobs

  resources :book_fragments

  
  modified_config = ActiveAdmin::Devise.config.clone
  modified_config[:controllers][:registrations] = 'registrations'
  devise_for :users, modified_config

  ActiveAdmin.routes(self)

  get "daisy_book/get_xml_with_descriptions"
  get "daisy_book/get_daisy_with_descriptions"
  get "daisy_book/process"
  get "daisy_book/image_check"
  get "daisy_book/download_daisy_with_descriptions", :as => :download_daisy_with_descriptions
  get "daisy_book/poll_daisy_with_descriptions", :as => :poll_daisy_with_descriptions
  
  post "daisy_book/submit_to_get_descriptions"
  post "daisy_book/check_image_coverage"

  post "upload_book/submit"
  get "upload_book/upload"

  get "edit_book/content"
  get "edit_book/local_file"
  get "edit_book/s3_file"
  get "edit_book/describe"
  get "edit_book/edit"

  get "edit_book/edit_side_bar_only"
  get "edit_book/edit_content_only"

  get "edit_book/side_bar"
  get "edit_book/book_header"

  get "books/get_books_with_images"
  get "books/get_latest_descriptions"
  get "books/get_approved_book_stats"
  post "books/mark_approved"

  get "api/get_approved_descriptions_and_book_stats"
  get "api/get_approved_book_stats"
  get "api/get_approved_descriptions"
  get "api/get_approved_stats"
  get "api/get_approved_content_models"
  get "api/get_image_approved"

  get "reports/index"
  get "reports/update_book_stats"
  get "reports/describer_list"
  get "reports/view_book"
  match "reports", :controller => 'reports', :action => 'index'

  get "repository/cleanup"
  get "repository/expire_cached"

  resources :users
  resources :dynamic_descriptions
  resources :books
  resources :dynamic_images

  resources :descriptions

  resources :images do
    resources :descriptions
  end

  resources :libraries

  match "book_list", :controller => 'books', :action => 'book_list'
  match "book_list_by_user", :controller => 'books', :action => 'book_list_by_user'
  match "daisy_book/describe", :controller => 'edit_book', :action => 'describe'
  match "edit_book/help", :controller => 'edit_book', :action => 'help'
  match "edit_book/description_guidance", :controller => 'edit_book', :action => 'description_guidance'
  match "update_descriptions_in_book/upload" => "update_descriptions_in_book#upload", :via => "post"
  match "update_descriptions_in_book" => "update_descriptions_in_book#index", :via => "get"
  match "user/terms_of_service", :controller => 'users', :action => 'terms_of_service'
  get "home/index"

  match "imageDesc", :to => "dynamic_images#show", :via => "get"
  match "imageDescriptions", :to => "dynamic_images#show_history", :via => "get"
  match "imageDesc/dynamic_images/:id", :to => "dynamic_images#update", :via => "post"
  match "imageDesc", :to => "dynamic_descriptions#create", :via => "post"
  match "imageDesc/mark_all_essential", :to => "dynamic_images#mark_all_essential", :via => "post"

  match "cm/:dynamic_image_id/current.xml", :to => "api#get_image_approved", :via => "get"

  match "file/*directory/*file", :controller => 'file', :action => 'file'
  match "file/*file", :controller => 'file', :action => 'file'
  match "admin_book_delete", :controller => 'books', :action => 'delete'
  match 'dynamic_descriptions_search', :controller => 'dynamic_descriptions', :action => 'search'
  
  match 'dynamic_images_sample_html/:id', :controller => 'dynamic_images', :action => 'category_sample_html_page'

  
  root :to => "home#index"

end

app/helpers/daisy_book_helper.rb
module DaisyBookHelper
  class BatchHelper
    ROOT_XPATH = "/xmlns:dtbook"
    def self.batch_add_descriptions_to_book job_id, current_library
      DaisyBookHelper::BatchHelper.batch_add_descriptions_to_book job_id, current_library
    end
    def self.batch_add_descriptions_to_book job_id, current_library
      p "ESH: 3333333 in batch_add_descriptions_to_book with job_id=#{job_id}"
      job = Job.where(:id => job_id).first
      # Retrieve file from S3
      repository = RepositoryChooser.choose
      enter_params = job.json_enter_params
      password = enter_params['password']
      random_uid = enter_params['random_uid']
      random_uid_book_location = repository.read_file(random_uid, File.join( "", "tmp", "#{random_uid}.zip"))
      zip_directory, book_directory, daisy_file = UnzipUtils.accept_book(random_uid_book_location)
      book = File.open daisy_file
      unless password.blank?
        begin
          Zip::Archive.decrypt(book.path, password)
        rescue Zip::Error => e
          ActiveRecord::Base.logger.info "#{e.class}: #{e.message}"
          if e.message.include?("Wrong password")
            ActiveRecord::Base.logger.info "Invalid Password for encyrpted zip"
            flash[:alert] = "Please check your password and re-enter"
          else
            ActiveRecord::Base.logger.info "Other problem with encrypted zip"
            flash[:alert] = "There is a problem with this zip file"
          end
          redirect_to :action => 'process'
          return
        end
      end

      if !DaisyUtils.valid_daisy_zip?(book.path)
        flash[:alert] = "Not a valid DAISY book"
        redirect_to :action => 'process'
        return
      end
    
      begin
        zip_directory, book_directory, daisy_file = UnzipUtils.accept_book(book.path)
        get_daisy_with_descriptions zip_directory, book_directory, daisy_file, job, current_library
      rescue Zip::Error => e
        ActiveRecord::Base.logger.info "#{e.class}: #{e.message}"
        if e.message.include?("File encrypted")
          ActiveRecord::Base.logger.info "Password needed for zip"
          flash[:alert] = "Please enter a password for this book"
        else
          ActiveRecord::Base.logger.info "Other problem with zip"
          flash[:alert] = "There is a problem with this zip file"
        end

        redirect_to :action => 'process'
        return
      end
    end
  
    def self.get_daisy_with_descriptions zip_directory, book_directory, daisy_file, job, current_library
      begin
        contents_filename = get_daisy_contents_xml_name(book_directory)
        relative_contents_path = contents_filename[zip_directory.length..-1]
        if(relative_contents_path[0,1] == '/')
          relative_contents_path = relative_contents_path[1..-1]
        end
        xml = get_xml_contents_with_updated_descriptions(contents_filename, current_library)
        zip_filename = create_zip(daisy_file, relative_contents_path, xml)
        basename = File.basename(contents_filename)
        ActiveRecord::Base.logger.info "Sending zip #{zip_filename} of length #{File.size(zip_filename)}"
      
        # Store this file in S3, update the Job; change exit_params and the state
        random_uid = UUIDTools::UUID.random_create.to_s
        repository = RepositoryChooser.choose
        repository.store_file(zip_filename, 'delayed', random_uid, nil) #store file in a directory
        job.update_attributes :state => 'complete', :exit_params => ({:basename => basename, :random_uid => random_uid}).to_json
      rescue ShowAlertAndGoBack => e
        p "ESH: have an error e=#{e.inspect}, trace=#{e.backtrace.inspect}"
        flash[:alert] = e.message
        job.update_attributes :state => 'error', :error_explanation => 'Unable to process this book at this time.  Please contact your Poet administrator.'
        redirect_to :action => 'process'
        return
      end
    end
    
    def self.get_daisy_contents_xml_name(book_directory)
      return Dir.glob(File.join(book_directory, '*.xml'))[0]
    end
    
    def self.get_xml_contents_with_updated_descriptions(contents_filename, current_library)
      xml_file = File.read(contents_filename)
      begin
        xml = get_contents_with_updated_descriptions(xml_file, current_library)
      rescue NoImageDescriptions
        ActiveRecord::Base.logger.info "No descriptions available #{contents_filename}"
        raise ShowAlertAndGoBack.new("There are no image descriptions available for this book")
      rescue NonDaisyXMLException => e
        ActiveRecord::Base.logger.info "Uploaded non-dtbook #{contents_filename}"
        raise ShowAlertAndGoBack.new("Uploaded file must be a valid Daisy book XML content file")
      rescue MissingBookUIDException => e
        ActiveRecord::Base.logger.info "Uploaded dtbook without UID #{contents_filename}"
        raise ShowAlertAndGoBack.new("Uploaded Daisy book XML content file must have a UID element")
      rescue Nokogiri::XML::XPath::SyntaxError => e
        ActiveRecord::Base.logger.info "Uploaded invalid XML file #{contents_filename}"
        ActiveRecord::Base.logger.info "#{e.class}: #{e.message}"
        ActiveRecord::Base.logger.info "Line #{e.line}, Column #{e.column}, Code #{e.code}"
        raise ShowAlertAndGoBack.new("Uploaded file must be a valid Daisy book XML content file")
      rescue Exception => e
        ActiveRecord::Base.logger.info "Unexpected exception processing #{contents_filename}:"
        ActiveRecord::Base.logger.info "#{e.class}: #{e.message}"
        ActiveRecord::Base.logger.info e.backtrace.join("\n")
        $stderr.puts e
        raise ShowAlertAndGoBack.new("An unexpected error has prevented processing that file")
      end

      return xml
    end
    
    def self.create_zip(old_daisy_zip, contents_filename, new_xml_contents)
      new_daisy_zip = Tempfile.new('baked-daisy')
      new_daisy_zip.close
      FileUtils.cp(old_daisy_zip, new_daisy_zip.path)
      Zip::Archive.open(new_daisy_zip.path) do |zipfile|
        zipfile.num_files.times do |index|
          if(zipfile.get_name(index) == contents_filename)
            zipfile.replace_buffer(index, new_xml_contents)
            break
          end
        end
      end
      return new_daisy_zip.path
    end
    
    def get_description_count_for_book_uid(book_uid, current_library)
      DaisyBookHelper::BatchHelper.get_description_count_for_book_uid(book_uid, current_library)
    end
    def self.get_description_count_for_book_uid(book_uid, current_library)
      return DynamicImage.
          joins(:book).
          where(:books => {:uid => book_uid, :library_id => current_library.id}).
          count
    end
    
    def get_contents_with_updated_descriptions(file, current_library)
      DaisyBookHelper::BatchHelper.get_contents_with_updated_descriptions(file, current_library)
    end
    def self.get_contents_with_updated_descriptions(file, current_library)
      doc = Nokogiri::XML file

      root = doc.xpath(doc, ROOT_XPATH)
      if root.size != 1
        raise NonDaisyXMLException.new
      end

      book_uid = DaisyUtils.extract_book_uid(doc)

      if get_description_count_for_book_uid(book_uid, current_library) == 0
        raise NoImageDescriptions.new
      end

      book = Book.where(:uid => book_uid, :library_id => current_library.id).first
      matching_images = DynamicImage.where("book_id = ?", book.id).all
      matching_images.each do | dynamic_image |
        image_location = dynamic_image.image_location
        image = doc.at_xpath( doc, "//xmlns:img[@src='#{image_location}']")
        if !image
          ActiveRecord::Base.logger.info "Missing img element for database description #{book_uid} #{image_location}"
          next
        end

        dynamic_description = dynamic_image.best_description
        if(!dynamic_description)
          ActiveRecord::Base.logger.info "Image #{book_uid} #{image_location} is in database but with no descriptions"
          next
        end

        image_id = image['id']

        parent = image.at_xpath("..")
        imggroup = get_imggroup_parent_of(image)
        if(!imggroup)
          imggroup = Nokogiri::XML::Node.new "imggroup", doc
          imggroup['id'] =  "imggroup_#{image_id}"
          imggroup.parent = parent

          parent.children.delete(image)
          image.parent = imggroup
          parent = imggroup
        end

        prodnotes = imggroup.xpath(".//xmlns:prodnote")
        our_prodnote = nil
        prodnotes.each do | prodnote |
          if(prodnote['id'] == create_prodnote_id(image_id))
            our_prodnote = prodnote
          end
        end
        if(!our_prodnote)
          our_prodnote = Nokogiri::XML::Node.new "prodnote", doc 
          imggroup.add_child our_prodnote 
        end

        our_prodnote.add_child(dynamic_description.body)
        our_prodnote['render'] = 'optional'
        our_prodnote['imgref'] = image_id
        our_prodnote['id'] = create_prodnote_id(image_id)
        our_prodnote['showin'] = 'blp'
      end

      return doc.to_xml
    end
    
    def create_prodnote_id(image_id)
      DaisyBookHelper::BatchHelper.create_prodnote_id(image_id)
    end
    def self.create_prodnote_id(image_id)
      "pnid_#{image_id}"
    end
    
    
    def get_imggroup_parent_of(image_node)
      DaisyBookHelper::BatchHelper.get_imggroup_parent_of(image_node)
    end
    def self.get_imggroup_parent_of(image_node)
      node = image_node
      prevent_infinite_loop = 100
      while(node)
        if(node.node_name == "imggroup")
          return node
        end
        parent = node.at_xpath("..")
        if(!parent || parent == node || parent.node_name == "dtbook")
          break
        end
        node = parent
        prevent_infinite_loop -= 1
        if(prevent_infinite_loop < 0)
          raise "XML file image was nested more than 100 levels deep"
        end
      end
      return nil
    end
    
  end
end

app/views/daisy_book/check_image_coverage.erb
<div id= "active_admin_content" class="with_sidebar">
 <div id="main_content_wrapper">
 <div id="main_content">  
    <h1>Image Coverage Results</h1>
    <h2><%=	 @book_title %></h2>
    </br>    
    <h4><b>Prodnotes </b></h4> 
    <table border="0" cellspacting="0" cellpadding="0"  class="index_table" style="margin-bottom:100px !important">
      <thead><tr><th>Image/ID</th><th>Value</th></tr></thead><tr>  
      <tbody>
      <% @prodnotes_hash.keys.each do |key| %>
       <tr class= "odd"><td width="50%">
        <% if (key.is_a? DynamicImage) %>
           <%= key.xml_id%>
        <% else %>
           <%= key %>
        <% end %>
       </td>
       <td width= "60%">
        <% value = @prodnotes_hash[key]%>
        <div class='convert-to-iframe'>
          <%= value %>
        </div>
       </td> </tr>
      <% end %>
      <% if (@prodnotes_hash.keys.size == 0) %>
         <tr class= "odd"><td width="50%">No prodnotes</td><td width= "60%"></td></tr>
       <% end %>
      </tbody>
    </table>
    </br>  
    <h4><b>Captions</b></h4> 
    <table border="0" cellspacting="0" cellpadding="0" class="index_table" style="margin-bottom:100px !important">
      <thead><tr><th>Image/ID</th><th>Value</th></tr></thead><tr>  
       <tbody>
       <% @captions_hash.keys.each do |key| %>
       <tr class= "odd"><td width="50%"><%= key %></td>
       <td width= "60%">
       <% value = @captions_hash[key]%>
       <div class='convert-to-iframe'>
          <%= value %> 
       </div>
       </td> </tr>
       <% end %>
       
       <% if (@captions_hash.keys.size == 0) %>
         <tr class= "odd"><td width="50%">No captions</td><td width= "60%"></td></tr>
       <% end %>
      </tbody>
    </table>
    
    <h4><b>Alt texts</b></h4>
    <table border="0" cellspacting="0" cellpadding="0" class="index_table" style="margin-bottom:100px !important">
      <thead><tr><th>Image/ID</th><th>Value</th></tr></thead><tr>  
       <tbody>
       <% @alt_text_hash.keys.each do |key| %>
       <tr class= "odd"><td width="50%"><%= key %></td>
       <td width= "60%">
       <% value = @alt_text_hash[key]%>
       <div class='convert-to-iframe'>
          <%= value %>
       </div>
       </td> </tr>
       <% end %>

       <% if (@alt_text_hash.keys.size == 0) %>
          <tr class= "odd"><td width="50%">No alt texts</td><td width= "60%"></td></tr>
       <% end %>
      </tbody>
    </table>
 </div>
 
</div>

<div id="sidebar">
      <div class="sidebar_section panel">
            <div class="panel_contents"><table>
              <tr>
                <td align="right">Total images </td>
                <td align="right"><%= @num_images  %></td>
              </tr>
              <tr>
                <td align="right">Total prodnotes </td>
                <td align="right"><%= @prodnotes_hash.size %></td>
              </tr>
              <tr>
                <td align="right">Total captions </td>
                <td align="right"><%= @captions_hash.size %></td>
              </tr>
              <tr>
                <td align="right">Total  alt text </td>
                <td align="right"><%= @alt_text_hash.size %></td>
              </tr>   
            </table>
          </div>    
  </div>
  </div>
  
</div>  

app/views/daisy_book/image_check.html.erb
 <div style="margin: auto; width:700px; padding-top: 40px;" >
    <h1>Check Image Coverage</h1>
    </br>
    <p>
    To check image coverage for a DAISY 3 book, follow these steps:
    </p>
    <ol>
    <li>Click the Browse (or Choose File) button below, and select a DAISY 3 book (zip) file from your local drive to process.</li>
    <li>Click the Process button.</li>
    </ol>

    <%= form_tag("/daisy_book/check_image_coverage", {:multipart => true}) do %>
    <p><label for="upload_file">Select DAISY 3 book </label> :
    <%= file_field_tag 'book' %> </p>
    <%= submit_tag "Check" %>
    <% end %>
 </div>

app/views/daisy_book/process.html.erb
 <div style="margin: auto; width:700px; padding-top: 40px;" >
    <h1>Update DAISY Book Image Descriptions</h1>
    </br>
    <p>
    To insert image descriptions into a DAISY book from the Bookshare library, follow these steps:
    </p>
    <ol>
    <li>Click the Browse (or Choose File) button below, and select a DAISY book (zip) file from your local drive to process.</li>
    <li>If the book is password protected, enter your password in the field.</li>
    <li>Click the Process button.</li>
    </ol>
    <p>
    Any existing image descriptions will be added to the book,
    and the book will be returned to you as a new DAISY book (zip) file.
    </p> </br>

    <%= form_tag("/daisy_book/submit_to_get_descriptions", {:multipart => true}) do %>
    <p><label for="upload_file">Select DAISY book file</label> :
    <%= file_field_tag 'book' %> </p>
    <p><label for="upload_file">Enter password (if needed)</label> :
    <%= password_field_tag 'password' %> </p>
    <%= submit_tag "Process" %>
    <% end %>
 </div>

app/views/daisy_book/submit_to_get_descriptions.html.haml
.download_link
  Your request is being processed. When complete, a link will appear for you to click to download the file.


:javascript
  function doPoll(){
    $.get('#{poll_daisy_with_descriptions_path(:job_id => @job.id)}', function(data) {
      console.log("Have results");
      console.log(data);
      console.log("Not Complete:");
      console.log(data == 'Not Complete');
      console.log("Complete:");
      console.log(data == 'Complete');
      if(data == 'Complete') {
        $('.download_link').html("<a href='#{download_daisy_with_descriptions_path(:job_id => @job.id)}'> Click to download the book with updated image descriptions. </a>");
      }
      else if(data == 'Error') {
        // TODO ESH: add an error message back to the user 
        console.log("Error")
      }
      else {
        setTimeout(doPoll, 500);
      }
    });
  }
  doPoll();