config/routes.rb
DiagramRailsApp::Application.routes.draw do
  resources :jobs

  resources :book_fragments

  
  modified_config = ActiveAdmin::Devise.config.clone
  modified_config[:controllers][:registrations] = 'registrations'
  devise_for :users, modified_config

  ActiveAdmin.routes(self)

  get "daisy_book/get_xml_with_descriptions"
  get "daisy_book/get_daisy_with_descriptions"
  get "daisy_book/process"
  get "daisy_book/image_check"
  get "daisy_book/download_daisy_with_descriptions", :as => :download_daisy_with_descriptions
  get "daisy_book/poll_daisy_with_descriptions", :as => :poll_daisy_with_descriptions
  
  post "daisy_book/submit_to_get_descriptions"
  post "daisy_book/check_image_coverage"

  post "upload_book/submit"
  get "upload_book/upload"

  get "edit_book/content"
  get "edit_book/local_file"
  get "edit_book/s3_file"
  get "edit_book/describe"
  get "edit_book/edit"

  get "edit_book/edit_side_bar_only"
  get "edit_book/edit_content_only"

  get "edit_book/side_bar"
  get "edit_book/book_header"

  get "books/get_books_with_images"
  get "books/get_latest_descriptions"
  get "books/get_approved_book_stats"
  post "books/mark_approved"

  get "api/get_approved_descriptions_and_book_stats"
  get "api/get_approved_book_stats"
  get "api/get_approved_descriptions"
  get "api/get_approved_stats"
  get "api/get_approved_content_models"
  get "api/get_image_approved"

  get "reports/index"
  get "reports/update_book_stats"
  get "reports/describer_list"
  get "reports/view_book"
  match "reports", :controller => 'reports', :action => 'index'

  get "repository/cleanup"
  get "repository/expire_cached"

  resources :users
  resources :dynamic_descriptions
  resources :books
  resources :dynamic_images

  resources :descriptions

  resources :images do
    resources :descriptions
  end

  resources :libraries

  match "book_list", :controller => 'books', :action => 'book_list'
  match "book_list_by_user", :controller => 'books', :action => 'book_list_by_user'
  match "daisy_book/describe", :controller => 'edit_book', :action => 'describe'
  match "edit_book/help", :controller => 'edit_book', :action => 'help'
  match "edit_book/description_guidance", :controller => 'edit_book', :action => 'description_guidance'
  match "update_descriptions_in_book/upload" => "update_descriptions_in_book#upload", :via => "post"
  match "update_descriptions_in_book" => "update_descriptions_in_book#index", :via => "get"
  match "user/terms_of_service", :controller => 'users', :action => 'terms_of_service'
  get "home/index"

  match "imageDesc", :to => "dynamic_images#show", :via => "get"
  match "imageDescriptions", :to => "dynamic_images#show_history", :via => "get"
  match "imageDesc/dynamic_images/:id", :to => "dynamic_images#update", :via => "post"
  match "imageDesc", :to => "dynamic_descriptions#create", :via => "post"
  match "imageDesc/mark_all_essential", :to => "dynamic_images#mark_all_essential", :via => "post"

  match "cm/:dynamic_image_id/current.xml", :to => "api#get_image_approved", :via => "get"

  match "file/*directory/*file", :controller => 'file', :action => 'file'
  match "file/*file", :controller => 'file', :action => 'file'
  match "admin_book_delete", :controller => 'books', :action => 'delete'
  match 'dynamic_descriptions_search', :controller => 'dynamic_descriptions', :action => 'search'
  
  match 'dynamic_images_sample_html/:id', :controller => 'dynamic_images', :action => 'category_sample_html_page'

  
  root :to => "home#index"

end

app/models/dynamic_description.rb
class DynamicDescription < ActiveRecord::Base
  validates :body, :length => { :minimum => 2, :maximum => 16384 } , :presence => true
  #validates :submitter, :length => { :maximum => 255 }
  validates :dynamic_image_id, :presence => true

  belongs_to :dynamic_image
  belongs_to :book
  belongs_to :submitter, :class_name => 'User', :foreign_key => :submitter_id
  before_save :remove_body_tag
  
  include Tire::Model::Search
  include Tire::Model::Callbacks
  accepts_nested_attributes_for :dynamic_image, :allow_destroy => true
  
  index_name BONSAI_INDEX_NAME
  # TO RUN THE INDEX: bundle exec rake environment tire:import CLASS='DynamicDescription' FORCE=1 --trace
  
  # tire do
  #   mapping do
  #     indexes :body, :type => 'string'
  #   end
  # end
  
  settings :number_of_shards => 1,
           :number_of_replicas => 1,
           :analysis => {
                      :analyzer => {
                                 :str_search_analyzer => {
                                               :type => :custom,
                                               :tokenizer => :keyword,
                                               :filter => [:lowercase]
                                 },
                                 :str_index_analyzer => {
                                               :type => :custom,
                                               :tokenizer => :keyword,
                                               :filter => [:lowercase, :substring]
                                 }
                                 
                      },
                      :filter => {
                               :substring => {
                                          :type => "nGram",
                                          :min_gram => 3,
                                          :max_gram => 7
                               }
                      }
            }  do
    mapping do
      indexes :image_type, :as => 'DynamicDescription.connection.select_value("select dynamic_image.image_category_id from dynamic_images dynamic_image, dynamic_descriptions dyn_des where dyn_des.dynamic_image_id = dynamic_image.id and dyn_des.id = #{self.id}")'      
      indexes :dynamic_image_id, :type => 'integer'  
      indexes :isbn, :type => 'string', :index_analyzer => "str_index_analyzer", :search_analyzer => "str_search_analyzer", :as => 'DynamicDescription.connection.select_value("select book.isbn from books book, dynamic_descriptions dyn_des where dyn_des.book_id = book.id and dyn_des.id = #{self.id}")'
      indexes :title, :type => 'string', :index_analyzer => "str_index_analyzer", :search_analyzer => "str_search_analyzer", :as => 'DynamicDescription.connection.select_value("select book.title from books book, dynamic_descriptions dyn_des where dyn_des.book_id = book.id and dyn_des.id = #{self.id}")'
      indexes :body, :type => 'string', :index_analyzer => "str_index_analyzer", :search_analyzer => "str_search_analyzer"
      indexes :dynamic_description_library_id, :as => 'DynamicDescription.connection.select_value("select book.library_id from books book, dynamic_descriptions dyn_des where dyn_des.book_id = book.id and dyn_des.id = #{self.id}")'
      indexes :is_last_approved, :as => 'DynamicDescription.connection.select_value("select (select id from dynamic_descriptions inner_dd where inner_dd.dynamic_image_id = dynamic_descriptions.dynamic_image_id and date_approved is not null order by date_approved desc limit 1) = dynamic_descriptions.id from dynamic_descriptions where id = #{self.id}")'
    end
  end
  
  
  def as_json(options={})
    { :body => body # just use the attribute when no helper is needed
    }
  end
  
  def remove_body_tag
     self.body.gsub!(/&lt;body&gt;/i, '')
     self.body.gsub!(/&lt;\/body&gt;/i, '')
     self.body.gsub!(/&nbsp;/i , '&#160') 
  end
  
  def submitter_name
    if submitter 
      if !submitter.full_name.blank?
        submitter.full_name
      elsif !submitter.username.blank?
        submitter.username
      else 
        submitter.email
      end
    end
  end

end

app/controllers/dynamic_descriptions_controller.rb
class DynamicDescriptionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /dynamic_descriptions
  # GET /dynamic_descriptions.xml
  def initialize
    super()
    @repository = RepositoryChooser.choose
  end

  def index
    @dynamic_descriptions = DynamicDescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dynamic_descriptions }
    end
  end

  # GET /dynamic_descriptions/1
  # GET /dynamic_descriptions/1.xml
  def show

    @dynamic_description = DynamicDescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dynamic_description }
    end
  end

  # GET /dynamic_descriptions/new
  # GET /dynamic_descriptions/new.xml
  def new
    @dynamic_description = DynamicDescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dynamic_description }
    end
  end

  # GET /dynamic_descriptions/1/edit
  def edit
    @dynamic_description = DynamicDescription.find(params[:id])
  end

  # POST /dynamic_descriptions
  # POST /dynamic_descriptions.xml
  def create
    book = load_book
    if params[:dynamic_description] && params[:dynamic_description][:dynamic_image_id]
      @dynamic_image = DynamicImage.where(:id => params[:dynamic_description][:dynamic_image_id]).first
      book = @dynamic_image.book if @dynamic_image
      @dynamic_description = @dynamic_image.dynamic_descriptions.create(params[:dynamic_description].merge({:book_id => book.id, :submitter_id => current_user.id})) if params[:dynamic_description] && params[:dynamic_description].is_a?(Hash)
    else
      @dynamic_description = DynamicDescription.new
      @dynamic_description.body = "missing parameters"
      @missing_parameters = true
    end
    
    respond_to do |format|
      if @missing_parameters
        format.html { render :action => "new" }
        format.xml  { render :xml => @dynamic_description, :status => :non_authoritative_information }
        format.json  { render :json => @dynamic_description, :callback => params[:callback], :status => :non_authoritative_information }
      elsif @dynamic_description.save
        @dynamic_description.reload
        format.html { render :partial => 'dynamic_images/show_history_fragment', :locals => {:descriptions => [@dynamic_description] }}
        format.html { redirect_to(@dynamic_description, :notice => 'Dynamic description was successfully created.') }
        format.xml  { render :xml => @dynamic_description, :status => :created, :location => @dynamic_description }
        format.json  { render :json => {:submitter => @dynamic_description.submitter_name}, :callback => params[:callback]}
      else
        @book_id = book.id
        @image_location = params[:image_location]
        format.html { render :action => "new" }
        format.xml  { render :xml => @dynamic_description.errors, :status => :non_authoritative_information }
        format.json  { render :json => @dynamic_description.errors.full_messages, :callback => params[:callback], :status => 400 }
      end
    end
  end


  # DELETE /dynamic_descriptions/1
  # DELETE /dynamic_descriptions/1.xml
  def destroy
    @dynamic_description = DynamicDescription.find(params[:id])
    @dynamic_description.destroy

    respond_to do |format|
      format.html { redirect_to(dynamic_descriptions_url) }
      format.xml  { head :ok }
    end
  end

  def search 
    search_term = params['search']['term']
    search_title = params['search']['title']
    search_isbn = params['search']['isbn']
    search_image = params['search']['image']
    search_image_type = params['search']['image_type']
    user_library_id =  current_user.user_libraries.first.library_id
    
    if !search_term.blank? || !search_title.blank? || !search_isbn.blank? || !search_image.blank? || !search_image_type.blank? 
      @host =  @repository.get_host(request)
      @results = DynamicDescription.tire.search(:per_page => 20, :page => (params[:page] || 1)) do  
       query do
         boolean do
           must   { term :body, search_term } if search_term.present?
           must   { term :title, search_title } if search_title.present?
           must   { term :isbn, search_isbn } if search_isbn.present?
           must   { term :dynamic_image_id, search_image } if search_image.present?
           must   { term :image_type, search_image_type } if search_image_type.present?
           must   { term :is_last_approved, '1' }
           must   { term :dynamic_description_library_id, user_library_id}
         end
       end
      end
      @dynamic_description_hash = DynamicDescription.where(:id => @results.map(&:id)).all.inject({}){|acc, desc| acc[desc.id] = desc; acc}
    end
  end



end

app/helpers/dynamic_descriptions_helper.rb
module DynamicDescriptionsHelper
end

app/views/dynamic_descriptions/_form.html.erb
<%= form_for(@dynamic_description) do |f| %>
  <% if @dynamic_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dynamic_description.errors.count, "error") %> prohibited this description from being saved:</h2>

      <ul>
      <% @dynamic_description.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <input id="dynamic_description_uid" name="book_id" type="hidden" value= "<%= @book_id%>"/>
  </div>
    <div class="field">
    <input id="dynamic_description_image_location" name="image_location" type="hidden" value="<%= @image_location%>"/>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dynamic_descriptions/edit.html.erb
<h1>Editing dynamic_description</h1>

<%= render 'form' %>

<%= link_to 'Show', @dynamic_description %> |
<%= link_to 'Back', dynamic_descriptions_path %>

app/views/dynamic_descriptions/index.html.erb
<h1>Listing dynamic_descriptions</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Is current</th>
    <th>Submitter</th>
    <th>Date approved</th>
    <th>Dynamic image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dynamic_descriptions.each do |dynamic_description| %>
  <tr>
    <td><%= dynamic_description.body %></td>
    <td><%= dynamic_description.is_current %></td>
    <td><%= dynamic_description.submitter_name %></td>
    <td><%= dynamic_description.date_approved %></td>
    <td><%= dynamic_description.dynamic_image %></td>
    <td><%= link_to 'Show', dynamic_description %></td>
    <td><%= link_to 'Edit', edit_dynamic_description_path(dynamic_description) %></td>
    <td><%= link_to 'Destroy', dynamic_description, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dynamic description', new_dynamic_description_path %>

app/views/dynamic_descriptions/new.html.erb
<h1>New description</h1>

<%= render 'form' %>

<%= link_to 'Back', dynamic_descriptions_path %>

app/views/dynamic_descriptions/search.html.erb
<div style="margin-left: 50px; width:900px; padding-top: 40px;" >
 <h2> Matching Descriptions</h2>
 
 <p><p><p>
   
  <table style='width: 100%;'>
     <tr>
       <td style='width: 200px;'>
         <div style="border: solid 0 #060; border-right-width:2px; padding-right:0.5ex">
         <b> Search Filters </b></br>
         </br>
          <table style="width:100px">
         <%= form_for :search, :url => dynamic_descriptions_search_path do |f|%>
            <tr>
            <td><%= f.label :title,  'Title:'  %></td>
            <td><%= f.text_field :title, options={:style=> "width: 100px;"} %></td>
            </tr><tr>
            <td><%= f.label :isbn,  'ISBN:'  %></td>
            <td><%= f.text_field :isbn, options={:style=> "width: 100px;"} %></td>
            </tr><tr>
            <td><%= f.label :image,  'Image:'  %></td>
            <td><%= f.text_field :image, options={:style=> "width: 100px;"} %></td>
            </tr><tr>
            <td><%= f.label :term,  'Descriptions:'  %></td>
            <td><%= f.text_field :term, options={:style=> "width: 100px;"} %></td>
            </tr><tr>
             <td><%= f.label :image_type,  'Image Type:'  %></td>
              <td>
               <%= f.select :image_type,  ImageCategory.order(:order_to_display).all.map {|category| [category.name, category.id]}, {:include_blank => 'None', :custom_label => 'Category'}%>
             </td>
            </tr>
          </table>
          <div align="right">
            <%= f.submit "Search" %>
          </div>
         <% end %>
        </div>
       </td>
       <td>
        


  <% if @results.blank? || @results.size < 1 %>

    <div style="margin: auto; text-align: center; font-weight: bold; color:red; padding: 5px; border-width: 4px; border-style: ridge; border-color: yellow;" >
      No results found</div>

  <% else%>

   <% @results.each do |result| %> 

   <% dynamic_description = @dynamic_description_hash[result.id.to_i]

      image = dynamic_description.dynamic_image
      xml_id = image.xml_id
      raw_src = image.image_location
      src = "book/#{raw_src}"
      book = dynamic_description.book
      model =  image


      %>
  <table class="outer-table-wrapper">
    <tbody>
    <tr>
    <td style='width: 200px;'>
      <div id="div_<%= src %>" style="padding-left: 5px;">
       <img style="padding-top: 55px;"
         alt="Image <%= model.id %>. Clicking will cause the frame to the right to scroll to this image within the book." src="<%= model.medium_source(@host)%>">
       </img>
       </br><b>Image:</b>  <a href="/edit_book/edit?book_id=<%= dynamic_description.try(:book).try(:id) %>" href="#<%= xml_id %>"><%= model.id %></a> </br>
    </td>
    <td> 
       </br>
       </br>       
       </br>
       </br>
       <b>Title:</b> <%= dynamic_description.try(:book).try(:title) %> </br>
       
       <b>ISBN:</b> <%= dynamic_description.try(:book).try(:isbn) %> </br>

       <b>Image Type:</b> 
       <%= ImageCategory.find(image.try(:image_category_id)).try(:name) if image.image_category_id%></br>
       </td>
       
      </div>      

     </td>
      </tr>
      <tr>
        <td span="2">
        <b>Image Description:</b> </br>
        <%= truncate(dynamic_description.body, :length => 175) %>
        </td>
      </tr>
    </tbody>
   </table>
    <hr>


  <% end%> 
 <%= paginate @results %>
 <% end %>
 </td>
</table>

app/views/dynamic_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @dynamic_description.body %>
</p>


<!-- <%= link_to 'Edit', edit_dynamic_description_path(@dynamic_description) %> |
<%= link_to 'Back', dynamic_descriptions_path %>  -->