config/routes.rb
DiagramRailsApp::Application.routes.draw do
  resources :jobs

  resources :book_fragments

  
  modified_config = ActiveAdmin::Devise.config.clone
  modified_config[:controllers][:registrations] = 'registrations'
  devise_for :users, modified_config

  ActiveAdmin.routes(self)

  get "daisy_book/get_xml_with_descriptions"
  get "daisy_book/get_daisy_with_descriptions"
  get "daisy_book/process"
  get "daisy_book/image_check"
  get "daisy_book/download_daisy_with_descriptions", :as => :download_daisy_with_descriptions
  get "daisy_book/poll_daisy_with_descriptions", :as => :poll_daisy_with_descriptions
  
  post "daisy_book/submit_to_get_descriptions"
  post "daisy_book/check_image_coverage"

  post "upload_book/submit"
  get "upload_book/upload"

  get "edit_book/content"
  get "edit_book/local_file"
  get "edit_book/s3_file"
  get "edit_book/describe"
  get "edit_book/edit"

  get "edit_book/edit_side_bar_only"
  get "edit_book/edit_content_only"

  get "edit_book/side_bar"
  get "edit_book/book_header"

  get "books/get_books_with_images"
  get "books/get_latest_descriptions"
  get "books/get_approved_book_stats"
  post "books/mark_approved"

  get "api/get_approved_descriptions_and_book_stats"
  get "api/get_approved_book_stats"
  get "api/get_approved_descriptions"
  get "api/get_approved_stats"
  get "api/get_approved_content_models"
  get "api/get_image_approved"

  get "reports/index"
  get "reports/update_book_stats"
  get "reports/describer_list"
  get "reports/view_book"
  match "reports", :controller => 'reports', :action => 'index'

  get "repository/cleanup"
  get "repository/expire_cached"

  resources :users
  resources :dynamic_descriptions
  resources :books
  resources :dynamic_images

  resources :descriptions

  resources :images do
    resources :descriptions
  end

  resources :libraries

  match "book_list", :controller => 'books', :action => 'book_list'
  match "book_list_by_user", :controller => 'books', :action => 'book_list_by_user'
  match "daisy_book/describe", :controller => 'edit_book', :action => 'describe'
  match "edit_book/help", :controller => 'edit_book', :action => 'help'
  match "edit_book/description_guidance", :controller => 'edit_book', :action => 'description_guidance'
  match "update_descriptions_in_book/upload" => "update_descriptions_in_book#upload", :via => "post"
  match "update_descriptions_in_book" => "update_descriptions_in_book#index", :via => "get"
  match "user/terms_of_service", :controller => 'users', :action => 'terms_of_service'
  get "home/index"

  match "imageDesc", :to => "dynamic_images#show", :via => "get"
  match "imageDescriptions", :to => "dynamic_images#show_history", :via => "get"
  match "imageDesc/dynamic_images/:id", :to => "dynamic_images#update", :via => "post"
  match "imageDesc", :to => "dynamic_descriptions#create", :via => "post"
  match "imageDesc/mark_all_essential", :to => "dynamic_images#mark_all_essential", :via => "post"

  match "cm/:dynamic_image_id/current.xml", :to => "api#get_image_approved", :via => "get"

  match "file/*directory/*file", :controller => 'file', :action => 'file'
  match "file/*file", :controller => 'file', :action => 'file'
  match "admin_book_delete", :controller => 'books', :action => 'delete'
  match 'dynamic_descriptions_search', :controller => 'dynamic_descriptions', :action => 'search'
  
  match 'dynamic_images_sample_html/:id', :controller => 'dynamic_images', :action => 'category_sample_html_page'

  
  root :to => "home#index"

end

app/models/book_fragment.rb
class BookFragment < ActiveRecord::Base
  belongs_to :book
end

app/controllers/book_fragments_controller.rb
class BookFragmentsController < InheritedResources::Base
end

app/helpers/book_fragments_helper.rb
module BookFragmentsHelper
end

app/views/book_fragments/_form.html.erb
<%= form_for(@book_fragment) do |f| %>
  <% if @book_fragment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_fragment.errors.count, "error") %> prohibited this book_fragment from being saved:</h2>

      <ul>
      <% @book_fragment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_fragments/edit.html.erb
<h1>Editing book_fragment</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_fragment %> |
<%= link_to 'Back', book_fragments_path %>

app/views/book_fragments/index.html.erb
<h1>Listing book_fragments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @book_fragments.each do |book_fragment| %>
  <tr>
    <td><%= link_to 'Show', book_fragment %></td>
    <td><%= link_to 'Edit', edit_book_fragment_path(book_fragment) %></td>
    <td><%= link_to 'Destroy', book_fragment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book fragment', new_book_fragment_path %>

app/views/book_fragments/new.html.erb
<h1>New book_fragment</h1>

<%= render 'form' %>

<%= link_to 'Back', book_fragments_path %>

app/views/book_fragments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_book_fragment_path(@book_fragment) %> |
<%= link_to 'Back', book_fragments_path %>