config/routes.rb
DiagramRailsApp::Application.routes.draw do
  resources :jobs

  resources :book_fragments

  
  modified_config = ActiveAdmin::Devise.config.clone
  modified_config[:controllers][:registrations] = 'registrations'
  devise_for :users, modified_config

  ActiveAdmin.routes(self)

  get "daisy_book/get_xml_with_descriptions"
  get "daisy_book/get_daisy_with_descriptions"
  get "daisy_book/process"
  get "daisy_book/image_check"
  get "daisy_book/download_daisy_with_descriptions", :as => :download_daisy_with_descriptions
  get "daisy_book/poll_daisy_with_descriptions", :as => :poll_daisy_with_descriptions
  
  post "daisy_book/submit_to_get_descriptions"
  post "daisy_book/check_image_coverage"

  post "upload_book/submit"
  get "upload_book/upload"

  get "edit_book/content"
  get "edit_book/local_file"
  get "edit_book/s3_file"
  get "edit_book/describe"
  get "edit_book/edit"

  get "edit_book/edit_side_bar_only"
  get "edit_book/edit_content_only"

  get "edit_book/side_bar"
  get "edit_book/book_header"

  get "books/get_books_with_images"
  get "books/get_latest_descriptions"
  get "books/get_approved_book_stats"
  post "books/mark_approved"

  get "api/get_approved_descriptions_and_book_stats"
  get "api/get_approved_book_stats"
  get "api/get_approved_descriptions"
  get "api/get_approved_stats"
  get "api/get_approved_content_models"
  get "api/get_image_approved"

  get "reports/index"
  get "reports/update_book_stats"
  get "reports/describer_list"
  get "reports/view_book"
  match "reports", :controller => 'reports', :action => 'index'

  get "repository/cleanup"
  get "repository/expire_cached"

  resources :users
  resources :dynamic_descriptions
  resources :books
  resources :dynamic_images

  resources :descriptions

  resources :images do
    resources :descriptions
  end

  resources :libraries

  match "book_list", :controller => 'books', :action => 'book_list'
  match "book_list_by_user", :controller => 'books', :action => 'book_list_by_user'
  match "daisy_book/describe", :controller => 'edit_book', :action => 'describe'
  match "edit_book/help", :controller => 'edit_book', :action => 'help'
  match "edit_book/description_guidance", :controller => 'edit_book', :action => 'description_guidance'
  match "update_descriptions_in_book/upload" => "update_descriptions_in_book#upload", :via => "post"
  match "update_descriptions_in_book" => "update_descriptions_in_book#index", :via => "get"
  match "user/terms_of_service", :controller => 'users', :action => 'terms_of_service'
  get "home/index"

  match "imageDesc", :to => "dynamic_images#show", :via => "get"
  match "imageDescriptions", :to => "dynamic_images#show_history", :via => "get"
  match "imageDesc/dynamic_images/:id", :to => "dynamic_images#update", :via => "post"
  match "imageDesc", :to => "dynamic_descriptions#create", :via => "post"
  match "imageDesc/mark_all_essential", :to => "dynamic_images#mark_all_essential", :via => "post"

  match "cm/:dynamic_image_id/current.xml", :to => "api#get_image_approved", :via => "get"

  match "file/*directory/*file", :controller => 'file', :action => 'file'
  match "file/*file", :controller => 'file', :action => 'file'
  match "admin_book_delete", :controller => 'books', :action => 'delete'
  match 'dynamic_descriptions_search', :controller => 'dynamic_descriptions', :action => 'search'
  
  match 'dynamic_images_sample_html/:id', :controller => 'dynamic_images', :action => 'category_sample_html_page'

  
  root :to => "home#index"

end

app/models/library.rb
class Library < ActiveRecord::Base
  validates :name,  :presence => true ,
                    :length => { :maximum => 128 }

  has_many :books, :dependent => :destroy
  has_many :images
  has_many :user_libraries, :dependent => :destroy
  has_many :users, :through => :user_libraries, :dependent => :destroy
  
  def related_books
    Book.where(:library_id => self.id).where("status <> 4").readonly(false)
  end
  
  def related_users
     User.joins(:user_libraries).where('user_libraries.library_id' => self.id).readonly(false)
  end
  
  def related_book_stats
     BookStats.joins(:book => :library).where(:libraries => {:id => self.id}).readonly(false)
  end  
  
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  # GET /libraries
  # GET /libraries.xml
  def index
    @libraries = Library.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @libraries }
    end
  end

  # GET /libraries/1
  # GET /libraries/1.xml
  def show
    @library = Library.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @library }
    end
  end

  # GET /libraries/new
  # GET /libraries/new.xml
  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @library }
    end
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.find(params[:id])
  end

  # POST /libraries
  # POST /libraries.xml
  def create
    @library = Library.new(params[:library])
    @library.id = SecureRandom.random_number(1000000)

    respond_to do |format|
      if @library.save
        format.html { redirect_to(@library, :notice => 'Library was successfully created.') }
        format.xml  { render :xml => @library, :status => :created, :location => @library }
        format.json  { render :json => @library, :status => :created, :location => @library }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @library.errors, :status => :unprocessable_entity }
        format.json  { render :json => @library.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /libraries/1
  # PUT /libraries/1.xml
  def update
    @library = Library.find(params[:id])

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to(@library, :notice => 'Library was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @library.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.xml
  def destroy
    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to(libraries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Listing libraries</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libraries.each do |library| %>
  <tr>
    <td><%= library.id %></td>
    <td><%= library.name %></td>
    <td><%= link_to 'Show', library %></td>
    <td><%= link_to 'Edit', edit_library_path(library) %></td>
    <td><%= link_to 'Destroy', library, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @library.id %>
</p>

<p>
  <b>Name:</b>
  <%= @library.name %>
</p>


<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>